### PR TITLE
Original tye

### PR DESCRIPTION
**Pull request by Mrxx99**
This adds all commit from https://github.com/microsoft/vscode-tye main branch.

I will add the tye2 edit on top, so this PR is only the original source

### CODE REVIEW

**Review by razvangoga — APPROVED** [review]

**Comment by razvangoga** [comment]
@Mrxx99 i should merge this with a normal merge commit and not a squash, right?

**Comment by Mrxx99** [comment]
> @Mrxx99 i should merge this with a normal merge commit and not a squash, right?

yes, I would go with normal merge

**Comment by Mrxx99** [comment]
Btw, I also have permission to merge (with a approval from you as requirement)

**Comment by razvangoga** [comment]
then do it

**Pull request merged**
